language: node_js
node_js:
  - "6.17"
  - "7.10"
  - "8.16"
  - "9.11"
  - "10.15"
  - "11.16"
sudo: false
dist: trusty
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
before_script:
  - npm run test:install
  - npm run lint:install
script:
  - npm test
  - npm run lint
