language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.9"
  - "5.12"
  - "6.17"
  - "7.10"
  - "8.16"
  - "9.11"
  - "10.15"
  - "11.14"
sudo: false
dist: trusty
cache:
  directories:
    - node_modules
before_script:
  - npm run test-install
script:
  - npm test
