language: node_js
node_js:
  # Note that eslint >=6 only support node >=8
  - 8
  - 10
  - 12
  - 13
  - 14
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm i
before_script:
  - npm run test:install
  - npm run lint:install
script:
  - npm test
  - npm run lint
